### ISSUE TITLE
add tool for creating graphql server 

### ISSUE THREAD

**Issue by keski** [LiUGraphQL/woo.sh#43]
This tool should be extracted from the current `mediator-service` in GitLab. The goal is to be able to generate a the files necessary for automatically setting up a basic GraphQL server, based on a given GraphQL API schema and the corresponding resolver functions. The backend of the generated server should be configurable (i.e., not hard coded). It should be possible, starting from a GraphQL DB schema, to set up a working GraphQL server configured for a particular database backend.

Importantly, everything included in this tool **MUST** be unrelated to anything SPIRIT specific.

**Comment by keski** [comment]
See branch [add-tool-for-creating-graphql-server](https://github.com/LiUGraphQL/woo.sh/tree/add-tool-for-creating-graphql-server)

@hartig Could you take a look at this setup and provide some feedback? If you look at the build script (`build.sh`) in the project root I think you'll get a basic idea of how it all comes together.

**Comment by hartig** [comment]
Robin, this looks quite good already!!

A few changes:
1. The directory 'examples' should be renamed to 'example'.
2. This 'example' directory should contain **only** the input files but not the output files. In fact, the output files should not be contained at all in the repo.
3. This 'example' directory should contain **all** the input files needed for generating the example server; that is, in addition to the DB schema, the following files should go there: 'api-schema-custom-extensions.graphql' and 'custom-resolvers.js'
4. The subdirectory 'schema' in this 'example' directory should be renamed to 'db-schema'
5. ...and the example DB schema file within this subdirectory should be renamed to 'starwars-db.graphql'
6. Similarly, the generated subdirectory 'api' should be renamed to 'api-schema'.
7. In 'build.sh', there should only be two directories that the user is encouraged to specify: the root directory with all the input and the root directory for all the output. The default values for these should be:
     * `$(pwd)/example/`   (Note that, instead of `${root}`, I deliberately use `$(pwd)` here; this is to avoid the impression that the input directory must be maintained as a subdirectory within the woo.sh directory structure.)
     * `$(pwd)/generated-example-server/`  (Not `bin/` !)
8. Related to the previous point, the other variables that you declare in 'build.sh' to point to specific input or output files should be moved into a separate block of lines (separate from the lines in which the user is encouraged to specify the two root directories, see previous point). Of course, the user may still tinker with these additional variable declarations, but the separation should make clear that this is not the main intention.
9. The script 'build.sh' should be renamed to 'woo.sh'!! (Otherwise, what would be the fun of execution it ;)

**Comment by hartig** [comment]
Robin, notice also that your branch is probably incompatible with PR #42 created by @epii-1 
Moreover, there are merge requests in the gitlab repo that extend the generator tool and the 'arangodb-tools.js' file. These changes need to be carried over to your branch here as well.

**Comment by keski** [comment]
Resolved (see https://github.com/LiUGraphQL/woo.sh/pull/46)
