### ISSUE TITLE
JavaScript testing

### ISSUE THREAD

**Issue by epii-1** [LiUGraphQL/woo.sh#94]
Currently there are no automated testing for the JavaScript components. Some tests will be added soon(ish) for the directives, and maybe more in the future.

Do we want automation for these tests? If so, what framework would we prefer?

I suspect I will be gone before this is implemented, but as the tests for directives are soon to be merged, I might as well start the discussion.

@hartig @keski @rcapshaw

**Comment by keski** [comment]
We're now using `mocha` as the framework for automated tests. By default, all `.js` files in the `test/` directory are executed. `test/basic-aspi-tests.js` contains some basic API tests and demonstrates how a server is started, some tests executed, and the server is stopped.

These tests should aim at being independenent from the rest of the framework, i.e., rather than calling the API and resolver generators as part of the tests the generated (and possibly modified) files should be included in the test directory. It's also possible to provide the schema and resolvers inline.

@hartig @rcapshaw
